### ISSUE TITLE
ReferenceError: Can't find variable: ApiAIPlugin

### ISSUE THREAD

**Issue by xwang38** [api-ai/api-ai-cordova-sample#2]
Hi, after i git clone this sample, add iOS platform and then install the plugin by "cordova plugin add ai.api.apiaiplugin", I am still having this referenceError: Can't find variable: ApiAIPlugin whenever I click on the mic button in demo project. 
I have attched screenshot of my index.js. Could someone please look at it for me plz? Thanks!

<img width="621" alt="screen shot 2015-11-20 at 10 07 57 am" src="https://cloud.githubusercontent.com/assets/14284618/11304636/98c0071a-8f6e-11e5-8837-491498c171cc.png">

**Comment by xVir** [comment]
Hi, @xwang38 !
Sorry, I think the problem because of we just move plugin to the NPM repository and made some renaming... Please, give us time until Monday to check the problem.
Thanks!

**Comment by xVir** [comment]
Hi, @xwang38!
We just fixed the problem.
Please, remove old plugin with
```bash
cordova plugin rm ai.api.apiaiplugin
```
and install new version with
```bash
cordova plugin add cordova-plugin-apiai
```
Thanks!

**Comment by xwang38** [comment]
Hi @xVir 

Thanks for the update. But even after installing the new version with "cordova plugin add cordova-plugin-apiai", I am still having the same error of "ReferenceError: Can't find variable: ApiAIPlugin".

To be more specific, here is my installation process:
"git clone https://github.com/api-ai/api-ai-cordova-sample.git"
install ngCordova
Add to my index.js file (typically in js folder) in function onDeviceReady subscription key etc.
Add <script src="lib/ng-cordova-master/dist/ng-cordova.js"></script> in my index.html file
include ngCordova in my add.js. "var module = angular.module('app', ['onsen','ngCordova']);"

ps: I am using 5.4.0v cordova;

Thanks!

**Comment by xVir** [comment]
@xwang38 , please download and try to run this project https://www.dropbox.com/s/gx6359ehtuh8rkc/api-ai-cordova-sample.zip?dl=0 (execute `cordova run android`, no additional actions required)

**Comment by xwang38** [comment]
@xVir I appreciate your help. But I am kind of in the middle of building an IOS app. Therefore, I am looking for an API that could work on iOS platform.

Thanks!

**Comment by xVir** [comment]
@xwang38 then `cordova run ios` :)

**Comment by xVir** [comment]
Hi, @xwang38 ,
Did you try `cordova run ios` command?

**Comment by xwang38** [comment]
@xVir Thanks for asking. But still, not really.... I tried it on my simulator, on browser, on my real device(iPhone 5c). But I keep getting this error of "reference error: can't find variable APIAIPlugin"

**Comment by xVir** [comment]
@xwang38 did you try my sample app?

**Comment by xwang38** [comment]
@xVir Sorry for late reply. I have been working on finals lately. Actually, I tried your sample app and got this error

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.jar
     Required by:
         :android:unspecified
BUILD FAILED

Total time: 3.501 secs

/Users/wangsheng/Downloads/api-ai-cordova-sample/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Users/wangsheng/Downloads/api-ai-cordova-sample/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/wangsheng/Downloads/api-ai-cordova-sample/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
ERROR running one or more of the platforms: Error: /Users/wangsheng/Downloads/api-ai-cordova-sample/platforms/android/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project

I have the correct android path and have installed Android 6.0(API 23) and Android SDK platform tools (23.0.1) 
Thanks

**Comment by xwang38** [comment]
@xVir Hey! I just tried the sample app again. This time, it works!! I haven't changed anything but it just happens! Thanks for the help. And great job! Voice matches perfectly

**Comment by xVir** [comment]
@xwang38 Great! Feel free to ask any questions :)
